filemanager/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('util.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

util/urls.py
from django.urls import path
from . import views
from .views import *
from .forms import *

urlpatterns = [
    path('', views.home, name='util-home'),
    path('add-file/', FileCreateView.as_view(), name='util-add-file'),
    path('add-dir/', DirectoryCreateView.as_view(), name='util-add-directory'),
    path('delete/', views.delete, name='util-delete'),
    path('open-file/', views.open_file, name='util-open-file'),
    path('update-frama/', views.update_frama, name='util-update'),
    path('edit-code/', views.edit_code, name='util-edit-code'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User

util/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Directory(models.Model):
    name = models.CharField(max_length = 30)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    deleted = models.BooleanField(default = False)
    description = models.TextField(null = False)
    creation_date = models.DateTimeField(default = timezone.now)

    def __str__ (self):
        return self.name 

    def get_absolute_url(self):
        return ('/');

class File(models.Model):
    name = models.CharField(max_length = 30)
    owner = models.ForeignKey(User, on_delete = models.CASCADE)
    directory = models.ForeignKey(Directory, on_delete = models.CASCADE)
    content = models.FileField(upload_to = 'database')
    deleted = models.BooleanField(default = False)
    framapath = models.CharField(max_length = 50, default="/")
    description = models.TextField()
    creation_date = models.DateTimeField(default = timezone.now)

    def __str__ (self):
        return self.name + " [" + str(self.pk) + "] "+ self.framapath + " " + self.content.url

    def get_absolute_url(self):
        return ('/');

class FileSection(models.Model):
    name = models.CharField(max_length = 30)
    description = models.TextField()
    creation_date = models.DateTimeField(default = timezone.now)
    category = models.CharField(max_length = 30)
    status = models.CharField(max_length = 30)
    status_date = models.DateTimeField(default = timezone.now)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return ('/');

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

util/forms.py
from django.shortcuts import render, redirect
from .models import *
from django.views.generic import ListView, CreateView
from django.forms import ModelForm
from django.core.exceptions import ObjectDoesNotExist

class DirectoryCreateView(CreateView):
    model = Directory
    fields = ['name', 'description']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class FileForm(ModelForm):
    class Meta:
        model = File
        fields = ['name', 'owner', 'directory', 'content', 'description']

    def __init__(self, *args, **kwargs):
        owner = kwargs.pop('owner')
        super(FileForm, self).__init__(*args, **kwargs)
        self.fields['directory'].queryset = Directory.objects.filter(owner = owner).filter(deleted = False)
        self.fields['owner'].queryset = User.objects.filter(id = owner.id)

class FileCreateView(CreateView):
    form_class = FileForm
    template_name = 'util/file_form.html'

    def get_form_kwargs(self):
        kwargs = super(FileCreateView, self).get_form_kwargs()
        kwargs['owner'] = self.request.user
        return kwargs

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    return render(request, 'users/profile.html')

util/views.py
from django.shortcuts import render, redirect
from .models import *
from django.views.generic import ListView, CreateView
from django.forms import ModelForm
from django.core.exceptions import ObjectDoesNotExist
from django.views.decorators.clickjacking import xframe_options_exempt 
from django.http import JsonResponse
from django.core.files.base import ContentFile

def home(request):
    try:
        context = {
            'files': File.objects.filter(owner = request.user),
            'directories': Directory.objects.filter(owner = request.user),
        }
    except TypeError:
        context = {}
    return render(request, 'util/base.html', context)

def add_file(request):
    return render(request, 'util/add_file.html')

def add_dir(request):
    return render(request, 'util/directory_form.html')

@xframe_options_exempt
def delete(request):
    if request.POST:
        if request.POST.get('dirs', False):
            try: 
                to_del = Directory.objects.filter(owner = request.user).get(id = request.POST['dirs'])
                to_del.deleted = True
                to_del.save()
            except ObjectDoesNotExist:
                return redirect('/delete/')
            
        if request.POST.get('files', False):
            try:
                to_del = File.objects.filter(owner = request.user).get(id = request.POST['files'])
                to_del.deleted = True
                to_del.save()
            except ObjectDoesNotExist:
                return redirect('/delete/')

        return redirect('/delete/')

    context = {
        'files': File.objects.filter(owner = request.user),
        'directories': Directory.objects.filter(owner = request.user),
    }
    return render(request, 'util/delete.html', context)

def edit_code(request):
    if request.method == 'POST' and request.is_ajax():
        try:
            to_edit = File.objects.filter(owner = request.user).get(pk = int(request.POST['fileid']))
            to_edit.content.value = request.POST['newcontent']
            to_edit.content.save(to_edit.name, ContentFile(request.POST['newcontent']))
            to_edit.save(update_fields = ['content'])
            return JsonResponse({'status':'Success', 'msg': 'File updated!'})
        except ObjectDoesNotExist:
            return JsonResponse({'status':'Fail', 'msg': 'Object does not exist'})
    else:
        return JsonResponse({'status':'Fail', 'msg':'Not a valid request'})

def open_file(request):
    return render(request, 'util/open-file.html')

def update_frama(request):
    if request.method == 'POST' and request.is_ajax():
        try:
            to_edit = File.objects.filter(owner = request.user).get(pk = int(request.POST['fileid']))
            to_edit.framapath = request.POST['framapath']
            to_edit.save(update_fields = ['framapath'])
            return JsonResponse({'status':'Success', 'msg': 'Launched frama succesfully'})
        except ObjectDoesNotExist:
            return JsonResponse({'status':'Fail', 'msg': 'Object does not exist'})
    else:
        return JsonResponse({'status':'Fail', 'msg':'Not a valid request'})

users/templates/users/login.html
{% extends "util/form.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
            </small><br>
            <small class="text-muted">
                Or go back to <a class="ml-2" href="{% url 'util-home' %}">Main Page</a>
            </small>
        </div>
    </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "util/form.html" %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends "util/form.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <!-- FORM HERE -->
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends "util/form.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Register Form</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
            </small><br>
            <small class="text-muted">
                Or go back to <a class="ml-2" href="{% url 'util-home' %}">Main Page</a>
            </small>
        </div>
    </div>
{% endblock content %}

util/templates/util/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'util/main.css' %}"> -->
    
	  <script src="{% static 'util/script.js' %}"></script>
	  <script src="{% static 'util/jq.js' %}"></script>
    <link rel="stylesheet" type ="text/css" href="{% static 'util/style.css' %}">

    <script src="{% static 'util/codemirror.js' %}"></script>
    <link rel="stylesheet" type ="text/css" href="{% static 'util/codemirror.css' %}">
    <script src="{% static 'util/mode/javascript/javascript.js' %}" ></script>
    <script src="{% static 'util/mode/clike/clike.js' %}" ></script>
    <script src="{% static 'util/codemirror_script.js' %}" defer></script>
    

    {% if title %}
        <title>Filemanager - {{ title }}</title>
    {% else %}
        <title>Filemanager</title>
    {% endif %}
</head>
<body>
  <div class="topnav">
  {% if user.is_authenticated %}
    <a class="nav-item nav-link" onclick = 'launchFrama("{{  csrf_token  }}")'>Frama-C</a>
    <a class="nav-item nav-link" href="{% url 'util-delete' %}" style = "display: none;">Delete</a>
    <a class="nav-item nav-link" href="{% url 'util-add-file' %}">Add File</a>
    <a class="nav-item nav-link" href="{% url 'util-add-directory' %}">Add Directory</a>
    <a class="nav-item nav-link" onclick = "hideFocus()">Focus</a>
    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout, {{ user}} </a>
  {% else %}
    <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
    <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
  {% endif %}
  </div>
<div class="box">
  <div class = "files">
    {% for dir in directories %}
      {% if dir.deleted == False and dir.owner == user %}
        <div class = "dir" id = "dir-wrap-{{dir.pk}}">
          <div class = "dirname" id = "dir-{{dir.pk}}">{{dir.name}}</div>
          {% for file in dir.file_set.all %}
            {% if file.deleted == False %}
              <div class = "filename" id = "file-{{file.pk}}" onclick = 'markElement(this,"{{file.content.url}}", "{{file.framapath}}", "{{file.pk}}")'>{{file.name}}</div>
            {% endif %}
          {% endfor %}
        </div>
      {% endif %}
    {% endfor %}
    {% if user.is_authenticated %}
      <iframe id="iFrame1" src="{% url 'util-delete' %}" width="100%" 
      onload='javascript:(function(o){o.style.height=1.3*o.contentWindow.document.body.scrollHeight+"px";}(this));' 
      style="height:200px;width:100%;border:none;overflow:hidden;"></iframe>
    {% endif %}
  </div>  
  <div class="work-space">
    <div class="code">
      <div class="codeholder" id ="codeholdplace">
        {% if user.is_authenticated %}
          <textarea class="codemirror-textarea" id ="codemirror-textarea"></textarea>
          <button onclick='saveCode("{{  csrf_token  }}")'>Save Code</button>
        {% endif %}
      </div>
    </div>
    <div class="focus">
      <div class="focuscontent" id ="focuscontentplace">
      </div>  
      </div>
    <div class="tab">
      <div class="buttpanel">
        <button onclick = "setFramaBasic()">Basic</button>
        <button onclick = "setFramaProp()">Prop</button>
        <button onclick = "setFramaRte()">Rte</button>
        <button onclick = "setFramaBoth()">Both</button>
        </div> 

      <div id="tab1content" class="tabcontent">
        <div class = "incontent">
        <h2>Frama compilation mode</h2>
        <p id = "framacompile">frama-c -wp -wp-log="r:result.txt" filename.c</p>
        </div>
      </div>
    </div>
  </div>
</div>
<form id = "framaform" action="/"  method="post" style="display: none;">
  {% csrf_token %}
  <input type="text" name = "fileid" id = "fileid" required>
  <input type="text" name = "framapath" id = "framapath" required>
</form>

</body>
</html>

util/templates/util/delete.html
{% extends "util/form.html" %}
{% block content %}
{% load static %}
        <script src="{% static 'util/script.js' %}"></script>
	    <script src="{% static 'util/jq.js' %}"></script>
    <div class="content-section" style="margin-top: -20px;">
        <form method = "POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-0">Delete Directory</legend>
            </fieldset>
            <select name="dirs" id="dirs">
            {% for dir in directories %}
            {% if dir.deleted == False%}
              <option value="{{dir.id}}">{{dir.name}} ({{dir.id}})</option>
            {% endif %}
          {% endfor %}
        </select>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit" onclick="deleteDirectoryJs()">Delete</button>
            </div>
        </form>

        <form method = "POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom">Delete File</legend>
            </fieldset>
            <select name="files" id="files">
                {% for file in files %}
                  {% if file.deleted == False %}
                    <option value="{{file.id}}">{{file.name}} ({{file.id}})</option>
                  {% endif %}
                {% endfor %}
            </select>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit" onclick="deleteFileJs()">Delete</button>
            </div>
        </form>
    </div>


    <style>
    .dirname, .filename
    {
        margin-top: 3px;
        font-weight: bolder;
        font-size: 1.2em;
        padding: 3px;
    }

    button
    {
        margin-top: 10px;
    }
    </style>
{% endblock content %}

util/templates/util/directory_form.html
{% extends "util/form.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Add Directory</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Create new Directory</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Go back to <a class="ml-2" href="{% url 'util-home' %}">Main Page</a>
            </small>
        </div>
    </div>
{% endblock content %}

util/templates/util/edit.html
{% extends "util/form.html" %}
{% block content %}
{% load static %}
        <script src="{% static 'util/script.js' %}"></script>
	    <script src="{% static 'util/jq.js' %}"></script>
    <div class="content-section" style="margin-top: -20px;">
        TEST CODE MIRROR
    </div>

{% endblock content %}

util/templates/util/file_form.html
{% extends "util/form.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Add File</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Upload new file</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Go back to <a class="ml-2" href="{% url 'util-home' %}">Main Page</a>
            </small>
        </div>
    </div>
{% endblock content %}

util/templates/util/form.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'util/main.css' %}">

    {% if title %}
        <title>Django Filemanager - {{ title }}</title>
    {% else %}
        <title>Django Filemanager</title>
    {% endif %}
</head>
<body>
    <main role="main" class="container mt-5">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

util/templates/util/home.html
{% extends "util/base.html" %}
{% block content %}
    
{% endblock content %}

util/templates/util/open-file.html
<h1>open</h1>